[versions]
kotlin = "1.9.0"
exposed = "0.41.1"

[libraries]
exposed-core = { module = "org.jetbrains.exposed:exposed-core", version.ref = "exposed" }
exposed-dao = { module = "org.jetbrains.exposed:exposed-dao", version.ref = "exposed" }
exposed-jdbc = { module = "org.jetbrains.exposed:exposed-jdbc", version.ref = "exposed" }

postgresql = { module = "org.postgresql:postgresql", version = "42.5.1" }
h2 = { module = "com.h2database:h2", version = "2.2.220" }

[bundles]
exposedBundle = ["exposed-core", "exposed-dao", "exposed-jdbc"]

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }